# Generated by Django 4.1.6 on 2023-02-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=30)),
            ],
        ),
    ]
