# Generated by Django 4.1.6 on 2023-02-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0002_alter_sections_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catagory.sections')),
            ],
        ),
    ]
