# Generated by Django 4.1.6 on 2023-02-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
