# Generated by Django 4.1.6 on 2023-02-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0004_adduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('apiname', models.CharField(max_length=30)),
                ('apipassword', models.CharField(max_length=30)),
                ('apiemail', models.CharField(max_length=50)),
            ],
        ),
    ]
