# Generated by Django 4.1.6 on 2023-02-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0005_apiuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiuser',
            old_name='apipassword',
            new_name='apiaddress',
        ),
    ]
